services:
  - type: web
    name: cv-analysis-fe
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/recruitment-agency-fe/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
